"""ORM models. Importing this package registers every table on Base.metadata."""
from app.models.analytics import (
    Backtest,
    BankrollSnapshot,
    Bet,
    FeatureSnapshot,
    ModelPrediction,
    ModelVersion,
    TeamRating,
    ValueOpportunity,
)
from app.models.core import (
    ApiRequest,
    Bookmaker,
    Competition,
    DataQualityLog,
    Fixture,
    FixtureStatistic,
    LeagueSetting,
    Market,
    Odds,
    Player,
    PlayerStatistic,
    Result,
    Season,
    SystemSetting,
    Team,
    TeamStatistic,
    Weather,
)
from app.models.news import Injury, ManagerChange, Suspension, Transfer

__all__ = [
    "ApiRequest",
    "Backtest",
    "BankrollSnapshot",
    "Bet",
    "Bookmaker",
    "Competition",
    "DataQualityLog",
    "FeatureSnapshot",
    "Fixture",
    "FixtureStatistic",
    "Injury",
    "LeagueSetting",
    "ManagerChange",
    "Market",
    "ModelPrediction",
    "ModelVersion",
    "Odds",
    "Player",
    "PlayerStatistic",
    "Result",
    "Season",
    "Suspension",
    "SystemSetting",
    "Team",
    "TeamRating",
    "TeamStatistic",
    "Transfer",
    "ValueOpportunity",
    "Weather",
]
