"""initial schema

Revision ID: 17f992f36279
Revises: 
Create Date: 2026-08-30 18:55:30.111656
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '17f992f36279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_requests',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_requests_provider'), ['provider'], unique=False)

    op.create_table('backtests',
    sa.Column('strategy', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('breakdowns', sa.JSON(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=False),
    sa.Column('bets', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtests_strategy'), ['strategy'], unique=False)

    op.create_table('bankroll_snapshots',
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('starting_bankroll', sa.Float(), nullable=False),
    sa.Column('current_bankroll', sa.Float(), nullable=False),
    sa.Column('total_staked', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('open_bets', sa.Integer(), nullable=False),
    sa.Column('settled_bets', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bankroll_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bankroll_snapshots_as_of'), ['as_of'], unique=False)

    op.create_table('bookmakers',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_exchange', sa.Boolean(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('competitions',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('provider_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitions_source_id'), ['source_id'], unique=False)

    op.create_table('markets',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('group', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('feature_version', sa.String(length=30), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_version')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_name'), ['name'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('league_settings',
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_sample_size', sa.Integer(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('home_advantage', sa.Float(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id')
    )
    op.create_table('seasons',
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'year', name='uq_season')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_competition_id'), ['competition_id'], unique=False)

    op.create_table('teams',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('competition_id', sa.String(length=36), nullable=True),
    sa.Column('provider_ids', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_source_id'), ['source_id'], unique=False)

    op.create_table('fixtures',
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=True),
    sa.Column('home_team_id', sa.String(length=36), nullable=False),
    sa.Column('away_team_id', sa.String(length=36), nullable=False),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=120), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_fixture_source')
    )
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixtures_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index('ix_fixtures_comp_kickoff', ['competition_id', 'kickoff_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index('ix_fixtures_kickoff', ['kickoff_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_source_id'), ['source_id'], unique=False)

    op.create_table('manager_changes',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('manager_name', sa.String(length=120), nullable=True),
    sa.Column('previous_manager', sa.String(length=120), nullable=True),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('before_stats', sa.JSON(), nullable=False),
    sa.Column('after_stats', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manager_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manager_changes_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manager_changes_team_id'), ['team_id'], unique=False)

    op.create_table('players',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('provider_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)

    op.create_table('team_ratings',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.Column('attack', sa.Float(), nullable=True),
    sa.Column('defence', sa.Float(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_ratings', schema=None) as batch_op:
        batch_op.create_index('ix_rating_team_time', ['team_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_ratings_team_id'), ['team_id'], unique=False)

    op.create_table('team_statistics',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season_id', 'as_of', name='uq_team_stat')
    )
    with op.batch_alter_table('team_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_statistics_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_statistics_team_id'), ['team_id'], unique=False)

    op.create_table('data_quality_logs',
    sa.Column('fixture_id', sa.String(length=36), nullable=True),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_logs_fixture_id'), ['fixture_id'], unique=False)

    op.create_table('feature_snapshots',
    sa.Column('fixture_id', sa.String(length=36), nullable=False),
    sa.Column('feature_version', sa.String(length=30), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('data_quality', sa.Float(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_snapshots_fixture_id'), ['fixture_id'], unique=False)

    op.create_table('fixture_statistics',
    sa.Column('fixture_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('possession', sa.Float(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('corners_ht', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'team_id', name='uq_fixture_stat')
    )
    with op.batch_alter_table('fixture_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixture_statistics_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixture_statistics_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixture_statistics_team_id'), ['team_id'], unique=False)

    op.create_table('injuries',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('fixture_id', sa.String(length=36), nullable=True),
    sa.Column('player_importance', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injuries_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_injuries_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_injuries_team_id'), ['team_id'], unique=False)

    op.create_table('odds',
    sa.Column('fixture_id', sa.String(length=36), nullable=False),
    sa.Column('bookmaker_key', sa.String(length=50), nullable=False),
    sa.Column('market_key', sa.String(length=60), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('decimal_odds', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odds_bookmaker_key'), ['bookmaker_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index('ix_odds_fixture_market', ['fixture_id', 'market_key', 'selection'], unique=False)
        batch_op.create_index('ix_odds_fixture_time', ['fixture_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_source_id'), ['source_id'], unique=False)

    op.create_table('player_statistics',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('season_id', sa.String(length=36), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xa', sa.Float(), nullable=True),
    sa.Column('appearances', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_statistics_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_statistics_source_id'), ['source_id'], unique=False)

    op.create_table('results',
    sa.Column('fixture_id', sa.String(length=36), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.Column('home_goals_ht', sa.Integer(), nullable=True),
    sa.Column('away_goals_ht', sa.Integer(), nullable=True),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.Column('home_corners_ht', sa.Integer(), nullable=True),
    sa.Column('away_corners_ht', sa.Integer(), nullable=True),
    sa.Column('home_red_cards', sa.Integer(), nullable=True),
    sa.Column('away_red_cards', sa.Integer(), nullable=True),
    sa.Column('first_red_card_minute', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=1), nullable=True),
    sa.Column('abnormal_flags', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_results_source_id'), ['source_id'], unique=False)

    op.create_table('suspensions',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('fixture_id', sa.String(length=36), nullable=True),
    sa.Column('player_importance', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suspensions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suspensions_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suspensions_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suspensions_team_id'), ['team_id'], unique=False)

    op.create_table('transfers',
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('from_team_id', sa.String(length=36), nullable=True),
    sa.Column('to_team_id', sa.String(length=36), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('transfer_type', sa.String(length=30), nullable=True),
    sa.Column('player_importance', sa.Float(), nullable=True),
    sa.Column('impact_estimate', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_from_team_id'), ['from_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_to_team_id'), ['to_team_id'], unique=False)

    op.create_table('weather',
    sa.Column('fixture_id', sa.String(length=36), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('snow', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id')
    )
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_source_id'), ['source_id'], unique=False)

    op.create_table('model_predictions',
    sa.Column('fixture_id', sa.String(length=36), nullable=False),
    sa.Column('feature_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('feature_version', sa.String(length=30), nullable=False),
    sa.Column('market_key', sa.String(length=60), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('fair_odds', sa.Float(), nullable=True),
    sa.Column('expected_home', sa.Float(), nullable=True),
    sa.Column('expected_away', sa.Float(), nullable=True),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.Integer(), nullable=True),
    sa.Column('best_odds_at_prediction', sa.Float(), nullable=True),
    sa.Column('closing_odds', sa.Float(), nullable=True),
    sa.Column('clv', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], ),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_predictions_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index('ix_pred_fixture_market', ['fixture_id', 'market_key', 'selection'], unique=False)
        batch_op.create_index('ix_pred_model', ['model_name', 'model_version'], unique=False)

    op.create_table('value_opportunities',
    sa.Column('fixture_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('market_key', sa.String(length=60), nullable=False),
    sa.Column('market_group', sa.String(length=30), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('market_probability', sa.Float(), nullable=True),
    sa.Column('raw_implied_probability', sa.Float(), nullable=True),
    sa.Column('best_odds', sa.Float(), nullable=True),
    sa.Column('best_bookmaker', sa.String(length=50), nullable=True),
    sa.Column('median_odds', sa.Float(), nullable=True),
    sa.Column('bookmaker_count', sa.Integer(), nullable=False),
    sa.Column('fair_odds', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('value_label', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('data_quality', sa.Float(), nullable=False),
    sa.Column('value_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('no_bet_reasons', sa.JSON(), nullable=False),
    sa.Column('key_factors', sa.JSON(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=60), nullable=True),
    sa.Column('odds_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['model_predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('value_opportunities', schema=None) as batch_op:
        batch_op.create_index('ix_value_fixture', ['fixture_id', 'market_key', 'selection'], unique=False)
        batch_op.create_index(batch_op.f('ix_value_opportunities_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_value_opportunities_scan_date'), ['scan_date'], unique=False)
        batch_op.create_index('ix_value_score', ['value_score'], unique=False)

    op.create_table('bets',
    sa.Column('fixture_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('market_key', sa.String(length=60), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('bookmaker_key', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('stake_method', sa.String(length=20), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_odds', sa.Float(), nullable=True),
    sa.Column('clv', sa.Float(), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['value_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bets_fixture_id'), ['fixture_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bets_fixture_id'))

    op.drop_table('bets')
    with op.batch_alter_table('value_opportunities', schema=None) as batch_op:
        batch_op.drop_index('ix_value_score')
        batch_op.drop_index(batch_op.f('ix_value_opportunities_scan_date'))
        batch_op.drop_index(batch_op.f('ix_value_opportunities_fixture_id'))
        batch_op.drop_index('ix_value_fixture')

    op.drop_table('value_opportunities')
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_pred_model')
        batch_op.drop_index('ix_pred_fixture_market')
        batch_op.drop_index(batch_op.f('ix_model_predictions_fixture_id'))

    op.drop_table('model_predictions')
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_source_id'))

    op.drop_table('weather')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_to_team_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_source_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_from_team_id'))

    op.drop_table('transfers')
    with op.batch_alter_table('suspensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suspensions_team_id'))
        batch_op.drop_index(batch_op.f('ix_suspensions_source_id'))
        batch_op.drop_index(batch_op.f('ix_suspensions_fixture_id'))

    op.drop_table('suspensions')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_source_id'))

    op.drop_table('results')
    with op.batch_alter_table('player_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_statistics_source_id'))
        batch_op.drop_index(batch_op.f('ix_player_statistics_player_id'))

    op.drop_table('player_statistics')
    with op.batch_alter_table('odds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odds_source_id'))
        batch_op.drop_index(batch_op.f('ix_odds_recorded_at'))
        batch_op.drop_index('ix_odds_fixture_time')
        batch_op.drop_index('ix_odds_fixture_market')
        batch_op.drop_index(batch_op.f('ix_odds_fixture_id'))
        batch_op.drop_index(batch_op.f('ix_odds_bookmaker_key'))

    op.drop_table('odds')
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injuries_team_id'))
        batch_op.drop_index(batch_op.f('ix_injuries_source_id'))
        batch_op.drop_index(batch_op.f('ix_injuries_fixture_id'))

    op.drop_table('injuries')
    with op.batch_alter_table('fixture_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixture_statistics_team_id'))
        batch_op.drop_index(batch_op.f('ix_fixture_statistics_source_id'))
        batch_op.drop_index(batch_op.f('ix_fixture_statistics_fixture_id'))

    op.drop_table('fixture_statistics')
    with op.batch_alter_table('feature_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_snapshots_fixture_id'))

    op.drop_table('feature_snapshots')
    with op.batch_alter_table('data_quality_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_logs_fixture_id'))

    op.drop_table('data_quality_logs')
    with op.batch_alter_table('team_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_statistics_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_statistics_season_id'))

    op.drop_table('team_statistics')
    with op.batch_alter_table('team_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_ratings_team_id'))
        batch_op.drop_index('ix_rating_team_time')

    op.drop_table('team_ratings')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_source_id'))
        batch_op.drop_index(batch_op.f('ix_players_name'))

    op.drop_table('players')
    with op.batch_alter_table('manager_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manager_changes_team_id'))
        batch_op.drop_index(batch_op.f('ix_manager_changes_source_id'))

    op.drop_table('manager_changes')
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixtures_source_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_season_id'))
        batch_op.drop_index('ix_fixtures_kickoff')
        batch_op.drop_index(batch_op.f('ix_fixtures_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_competition_id'))
        batch_op.drop_index('ix_fixtures_comp_kickoff')
        batch_op.drop_index(batch_op.f('ix_fixtures_away_team_id'))

    op.drop_table('fixtures')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_source_id'))
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_competition_id'))

    op.drop_table('teams')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_competition_id'))

    op.drop_table('seasons')
    op.drop_table('league_settings')
    op.drop_table('system_settings')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_name'))

    op.drop_table('model_versions')
    op.drop_table('markets')
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitions_source_id'))

    op.drop_table('competitions')
    op.drop_table('bookmakers')
    with op.batch_alter_table('bankroll_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bankroll_snapshots_as_of'))

    op.drop_table('bankroll_snapshots')
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtests_strategy'))

    op.drop_table('backtests')
    with op.batch_alter_table('api_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_requests_provider'))

    op.drop_table('api_requests')
    # ### end Alembic commands ###
